### ISSUE TITLE
Link of weights not correct

### ISSUE THREAD

**Issue by johnskop7** [valentyn1boreiko/Fundus_VCEs#1]
Dear authors,
The link that you have provided for the download of the weights of a robust model trained with TRADES does not seem correct. It directs us to a dropbox page that does not contain anything. Could you please provide us with the correct link? Thank you very much !

**Comment by valentyn1boreiko** [comment]
Dear @johnskop7, thank you for notifying us. Now the link is updated. Please let me know, if it still does not work for you.

Best,
Valentyn
